import gamemoves as gm
import pyautogui
import time
import detect
from pynput.keyboard import Key, Controller

def point1(pic, i):
    pyautogui.keyDown('w')
    pyautogui.press('2')
    time.sleep(1.5)
    pyautogui.keyUp('w')
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.sevandfivedegreesmove()
    pyautogui.keyDown('w')
    time.sleep(3.9)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backsevandfivedegreesmove()
    pyautogui.keyDown('w')
    time.sleep(2.2)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    pyautogui.keyDown('w')
    time.sleep(3.2)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    pyautogui.keyDown('w')
    time.sleep(2.2)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    pyautogui.keyDown('w')
    time.sleep(2.7)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    pyautogui.keyDown('w')
    time.sleep(3.35)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    pyautogui.keyDown('w')
    time.sleep(7.2)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.sevandfivedegreesmove()
    pyautogui.keyDown('w')
    time.sleep(2.6)
    pyautogui.keyUp('w')
    time.sleep(0.5)
    gm.sevandfivedegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    time.sleep(0.35)
    pyautogui.press('m')
    time.sleep(0.5)
    pyautogui.moveTo(1855, 950, 0.2)
    time.sleep(0.3)
    pyautogui.click()
    time.sleep(0.15)
    pyautogui.click()
    time.sleep(0.15)
    pyautogui.click()
    time.sleep(0.15)
    pyautogui.click()
    time.sleep(0.15)
    pyautogui.moveTo(1860, 1010, 0.1)
    time.sleep(0.2)
    pyautogui.scroll(-1)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point2(pic, i):
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.onedegreemove()
    pyautogui.keyDown('w')
    time.sleep(4.25)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    pyautogui.keyDown('w')
    time.sleep(6.25)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    pyautogui.keyDown('w')
    time.sleep(3.25)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backsevandfivedegreesmove()
    pyautogui.keyDown('w')
    time.sleep(6.25)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backsevandfivedegreesmove()
    pyautogui.keyDown('w')
    time.sleep(6.25)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backsevandfivedegreesmove()
    pyautogui.keyDown('w')
    time.sleep(4)
    pyautogui.keyDown('a')
    time.sleep(1.1)
    pyautogui.keyUp('a')
    time.sleep(0.2)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.sevandfivedegreesmove()
    gm.backonedegreemove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point3(pic, i):
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(9.7)
    pyautogui.keyUp('w')
    time.sleep(0.5)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.35)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point4(pic, i):
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.sevandfivedegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(10)
    pyautogui.keyUp('w')
    time.sleep(0.5)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backsevandfivedegreesmove()
    time.sleep(0.35)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point5(pic, i):
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backsevandfivedegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(10.5)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.sevandfivedegreesmove()
    time.sleep(0.35)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point6(pic, i):
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backsevandfivedegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(10)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.sevandfivedegreesmove()
    time.sleep(0.35)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point7(pic, i):
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backsevandfivedegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(10)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.sevandfivedegreesmove()
    time.sleep(0.35)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point8(pic, i):
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.sevandfivedegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(10.5)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backsevandfivedegreesmove()
    time.sleep(0.35)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point9(pic, i):
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(8.5)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.35)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point10(pic, i):
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.sevandfivedegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(10.2)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.sevandfivedegreesmove()
    time.sleep(0.35)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point11(pic, i):
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(9.5)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.sevandfivedegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(4.65)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.sevandfivedegreesmove()
    time.sleep(0.35)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point12(pic, i):
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(8.8)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point13(pic, i):
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(4.2)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.sevandfivedegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(6.6)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.sevandfivedegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point14(pic, i):
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(9.5)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point15(pic, i):
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(19)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point16(pic, i):
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(9)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point17(pic, i):
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backsevandfivedegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(10)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.sevandfivedegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point18(pic, i):
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backsevandfivedegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(4.1)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(8)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backsevandfivedegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point19(pic, i):
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(2.5)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point20(pic, i):
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backsevandfivedegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(22.1)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.sevandfivedegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point21(pic, i):
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(10.6)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point22(pic, i):
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(6)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(4.2)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point22(pic, i):
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(8.5)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point23(pic, i):
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(9.5)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point24(pic, i):
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backsevandfivedegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(10.3)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.sevandfivedegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point25(pic, i):
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(10.2)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backsevandfivedegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(9.4)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.sevandfivedegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point26(pic, i):
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(8.5)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point27(pic, i):
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(11)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point28(pic, i):
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.sevandfivedegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(9.3)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backsevandfivedegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point29(pic, i):
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backsevandfivedegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(9.5)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.sevandfivedegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point30(pic, i):
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(12.5)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point31(pic, i):
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(9.7)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point32(pic, i):
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.sevandfivedegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(5.3)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(6)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backsevandfivedegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point33(pic, i):
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(10.2)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point34(pic, i):
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(4.5)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.sevandfivedegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(6)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backsevandfivedegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point35(pic, i):
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backsevandfivedegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(10)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.sevandfivedegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point36(pic, i):
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(10)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point37(pic, i):
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(4.5)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(5.5)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point38(pic, i):
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(10)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point39(pic, i):
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(12)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point40(pic, i):
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(6.7)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(12)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(4)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point41(pic, i):
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backsevandfivedegreesmove()
    time.sleep(0.5)
    pyautogui.keyDown('w')
    time.sleep(10)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.sevandfivedegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i

def point42(pic, i):
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    gm.backfifteendegreesmove()
    time.sleep(0.3)
    pyautogui.keyDown('w')
    time.sleep(10.4)
    pyautogui.keyUp('w')
    time.sleep(0.3)
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    gm.fifteendegreesmove()
    time.sleep(0.3)
    pyautogui.press('m')
    time.sleep(0.5)
    i = gm.hemplilbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hempbigbush(pic, i)
    i = gm.hemplilbush(pic, i)
    time.sleep(0.5)
    pyautogui.press('m')
    time.sleep(0.5)

    return i
